export { default as Account } from './components/Tabs'
export { default as Personal } from './components/profile/Personal'
export { default as Edit } from './components/Edit'
export { default as ChangePassword } from './components/security/changePassword/ChangePassword'
export { default as ForgotPassword } from './components/security/ForgotPassword'
export { default as LogoutForm } from './components/Logout/Logout'
export { default as Preferences } from './components/preferences'
export { default as Layout } from './components/index'
