export { default as Post } from './components/Feed'
export { default as AddPost } from './components/AddPost'
export { default as EditPost } from './components/EditPost'
export { default as PostDetails } from './components/Detail'
export { default as Mine } from './components/Mine'
